default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: korezawatenma
  password: <%= ENV['KEY'] %>
  host: localhost
  port: 5432

development:
  <<: *default
  database: sns_app_development

test:
  <<: *default
  database: sns_app_test

production:
  <<: *default
  database: sns_app_production
  username: korezawatenma
  password: <%= ENV['KEY'] %>
  host: localhost
